//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class xcTmpAgen
    {
        public string ef_cve { get; set; }
        public string tipo_doc { get; set; }
        public int num_fol { get; set; }
        public string articulos { get; set; }
        public string art_cve { get; set; }
        public Nullable<System.DateTime> fec_mov_ttant { get; set; }
        public Nullable<short> status_orden { get; set; }
        public string status_entrega { get; set; }
        public Nullable<double> uns_vta { get; set; }
        public string uni_med { get; set; }
        public Nullable<double> precio_vta { get; set; }
        public string calculo { get; set; }
        public string num_reng { get; set; }
        public string reng { get; set; }
    }
}
