//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class skytexEntities : DbContext
    {
        public skytexEntities()
            : base("name=skytexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<xcdconapl_cl> xcdconapl_cl { get; set; }
        public DbSet<xtPlaneacion> xtPlaneacion { get; set; }
        public DbSet<xcTmpAgen> xcTmpAgens { get; set; }
    
        public virtual ObjectResult<sp_ListaEventos_Result> sp_ListaEventos(string ef_cve, string tipdoc_cve, string extra)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var extraParameter = extra != null ?
                new ObjectParameter("extra", extra) :
                new ObjectParameter("extra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaEventos_Result>("sp_ListaEventos", ef_cveParameter, tipdoc_cveParameter, extraParameter);
        }
    
        public virtual ObjectResult<Eventos_Result> Eventos(string ef_cve, string tipdoc_cve, string status_proceso)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var status_procesoParameter = status_proceso != null ?
                new ObjectParameter("status_proceso", status_proceso) :
                new ObjectParameter("status_proceso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Eventos_Result>("Eventos", ef_cveParameter, tipdoc_cveParameter, status_procesoParameter);
        }
    
        public virtual int sp_WebAppAgActInfo(string ef_cve, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin, string id_maq, string id_bacth, string nom_batch, string doc_generar, string accion, string opcion, string user_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var id_maqParameter = id_maq != null ?
                new ObjectParameter("id_maq", id_maq) :
                new ObjectParameter("id_maq", typeof(string));
    
            var id_bacthParameter = id_bacth != null ?
                new ObjectParameter("id_bacth", id_bacth) :
                new ObjectParameter("id_bacth", typeof(string));
    
            var nom_batchParameter = nom_batch != null ?
                new ObjectParameter("nom_batch", nom_batch) :
                new ObjectParameter("nom_batch", typeof(string));
    
            var doc_generarParameter = doc_generar != null ?
                new ObjectParameter("doc_generar", doc_generar) :
                new ObjectParameter("doc_generar", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var opcionParameter = opcion != null ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(string));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_WebAppAgActInfo", ef_cveParameter, fec_iniParameter, fec_finParameter, id_maqParameter, id_bacthParameter, nom_batchParameter, doc_generarParameter, accionParameter, opcionParameter, user_cveParameter);
        }
    
        public virtual int sp_WebAppAgenActInfo(string ef_cve, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin, string id_maq, string id_bacth, string nom_batch, string doc_generar, string accion, string opcion, string user_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var id_maqParameter = id_maq != null ?
                new ObjectParameter("id_maq", id_maq) :
                new ObjectParameter("id_maq", typeof(string));
    
            var id_bacthParameter = id_bacth != null ?
                new ObjectParameter("id_bacth", id_bacth) :
                new ObjectParameter("id_bacth", typeof(string));
    
            var nom_batchParameter = nom_batch != null ?
                new ObjectParameter("nom_batch", nom_batch) :
                new ObjectParameter("nom_batch", typeof(string));
    
            var doc_generarParameter = doc_generar != null ?
                new ObjectParameter("doc_generar", doc_generar) :
                new ObjectParameter("doc_generar", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var opcionParameter = opcion != null ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(string));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_WebAppAgenActInfo", ef_cveParameter, fec_iniParameter, fec_finParameter, id_maqParameter, id_bacthParameter, nom_batchParameter, doc_generarParameter, accionParameter, opcionParameter, user_cveParameter);
        }
    
        public virtual ObjectResult<sp_WebAppLlenaLista_Result> sp_WebAppLlenaLista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppLlenaLista_Result>("sp_WebAppLlenaLista");
        }
    
        public virtual int sp_llenaAgenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_llenaAgenda");
        }
    
        public virtual ObjectResult<sp_WebAppAgMuestaEv1_Result> sp_WebAppAgMuestaEv1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppAgMuestaEv1_Result>("sp_WebAppAgMuestaEv1");
        }
    
        public virtual ObjectResult<sp_WebAppInsInfo_Result> sp_WebAppInsInfo(string ef_cve, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin, string id_maq, string id_bacth, string nom_batch, string doc_generar, string accion, string opcion, string user_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var id_maqParameter = id_maq != null ?
                new ObjectParameter("id_maq", id_maq) :
                new ObjectParameter("id_maq", typeof(string));
    
            var id_bacthParameter = id_bacth != null ?
                new ObjectParameter("id_bacth", id_bacth) :
                new ObjectParameter("id_bacth", typeof(string));
    
            var nom_batchParameter = nom_batch != null ?
                new ObjectParameter("nom_batch", nom_batch) :
                new ObjectParameter("nom_batch", typeof(string));
    
            var doc_generarParameter = doc_generar != null ?
                new ObjectParameter("doc_generar", doc_generar) :
                new ObjectParameter("doc_generar", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var opcionParameter = opcion != null ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(string));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppInsInfo_Result>("sp_WebAppInsInfo", ef_cveParameter, fec_iniParameter, fec_finParameter, id_maqParameter, id_bacthParameter, nom_batchParameter, doc_generarParameter, accionParameter, opcionParameter, user_cveParameter);
        }
    
        public virtual ObjectResult<sp_WebAppLlenaPlaneacion_Result> sp_WebAppLlenaPlaneacion(Nullable<short> status_proceso, string opcion, string user_cve, string ef_cve)
        {
            var status_procesoParameter = status_proceso.HasValue ?
                new ObjectParameter("status_proceso", status_proceso) :
                new ObjectParameter("status_proceso", typeof(short));
    
            var opcionParameter = opcion != null ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(string));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppLlenaPlaneacion_Result>("sp_WebAppLlenaPlaneacion", status_procesoParameter, opcionParameter, user_cveParameter, ef_cveParameter);
        }
    
        public virtual ObjectResult<sp_AgendaListaEventos_Result> sp_AgendaListaEventos(string ef_cve, string tipdoc_cve, string status_proceso)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var status_procesoParameter = status_proceso != null ?
                new ObjectParameter("status_proceso", status_proceso) :
                new ObjectParameter("status_proceso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AgendaListaEventos_Result>("sp_AgendaListaEventos", ef_cveParameter, tipdoc_cveParameter, status_procesoParameter);
        }
    
        public virtual ObjectResult<sp_WebAppActAgenda_Result> sp_WebAppActAgenda(string ef_cve, string doc_generar, string opcion)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var doc_generarParameter = doc_generar != null ?
                new ObjectParameter("doc_generar", doc_generar) :
                new ObjectParameter("doc_generar", typeof(string));
    
            var opcionParameter = opcion != null ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppActAgenda_Result>("sp_WebAppActAgenda", ef_cveParameter, doc_generarParameter, opcionParameter);
        }
    }
}
